name: Checks
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.4.0

      - name: Setup npm
        run: |
          npm set @kristijorgji:registry=https://npm.pkg.github.com/kristijorgji
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}"

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          npx lerna bootstrap

      - name: Run tests
        run: npx lerna exec npm run test
